modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "wwdatagen"
version = "${version}"
displayName = "WWDataGenerator"
authors = "To_Craft"
description = '''
Companion mod for the woodwalkers-mod, to help datapack creators, create awsome datapacks!
(Please consider sending your datapcks to me so other players can enjoy the enhanced gameplay :D )
'''
#logoFile = ""

[[dependencies.wwdatagen]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wwdatagen]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wwdatagen]]
modId = "craftedcore"
mandatory = true
versionRange = "[${craftedcore_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wwdatagen]]
modId = "walkers"
mandatory = true
versionRange = "[${woodwalkers_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wwdatagen]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"